Changed SSL certificate check to allow non self signed certificates

diff --git a/files/hooks/entrypoint-pre.d/20_ssl_setup b/files/hooks/entrypoint-pre.d/20_ssl_setup
--- a/files/hooks/entrypoint-pre.d/20_ssl_setup
+++ b/files/hooks/entrypoint-pre.d/20_ssl_setup
@@ -11,15 +11,22 @@ if [[ ! -e  "$SSL_KEY" ]] && [[ ! -e "$SSL_CERT" ]]; then
 elif [[ ! -z "$SSL_KEY" ]] && [[ ! -z "$SSL_CERT" ]]; then
 
 	KEYCHECK=`openssl rsa -in "$SSL_KEY" -check 2>&1 | grep --quiet "ok" ; echo $?`
-	CERTCHECK=`openssl x509 -in "$SSL_CERT" -text -noout 2>&1 | grep --quiet "CA:TRUE" ; echo $?`
 	if [ "$KEYCHECK" == "1"  ]; then
 		echo "Key is not valid. Configuration failed."
 		exit 1
 	fi
-	if [ "$CERTCHECK" == "1" ]; then
-		echo "Cert is not valid. Configuration failed."
-		exit 1
+
+	CACHECK=`openssl x509 -in "$SSL_CERT" -text -noout 2>&1 | grep --quiet "CA:TRUE" ; echo $?`
+	if [ "$CACHECK" == "0" ]; then
+		# This certificate is permitted to act as a Certificate Authority
+		SELFSIGNEDCHECK=`openssl verify "$SSL_CERT" 2>&1 | grep --quiet "self signed certificate"; echo $?`
+		if [ "$SELFSIGNEDCHECK" == "1" ]; then
+			# This certificate is NOT a self signed certificate, so we shouldn't allow it.
+			echo "Cert is not valid. Configuration failed."
+			exit 1
+		fi
 	fi
+
 	KEYMD5=`openssl rsa -noout -modulus -in "$SSL_KEY" | openssl md5 | sed 's/^.*= //'`
 	CERTMD5=`openssl x509 -noout -modulus -in "$SSL_CERT" | openssl md5 | sed 's/^.*= //'`
 	if [ "$KEYMD5" != "$CERTMD5" ]; then
